batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202503192030
train_epochs: 1000
train_workers: 20
vocab: xV"Ky'?L/JjS6WRt3P)*N#:07MXH4pUqa,YvOn5I.GdimF981TzQwCE+&o-ZlDsAekc;ubB!(r2ghf
width: 128
