batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202503192103
train_epochs: 1000
train_workers: 20
vocab: v0a)OH7Q81'pFXn?b+AuPMk:#i9JG*ElhfTsmogw/NRe4!S;tzBI2"-(3CDxyrZ,5cYj&6VLK.qWUd
width: 128
