batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202503192057
train_epochs: 1000
train_workers: 20
vocab: MzKhFc).3SCZ"mP-xiE0?I(fvVq'naXNsB/4rb5AuUw;dWpQOoyH97k1#8J2D*Ygl!&Rj6G+et:LT,
width: 128
