batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202503192034
train_epochs: 1000
train_workers: 20
vocab: c9wgZho"u?LO#lsqI3t4aSrbTkNm(XM'iE0!xRB:fnzAyC)5pQV1FG2,68YDd*jU./e;J+7vPKH&W-
width: 128
