batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202503192100
train_epochs: 1000
train_workers: 20
vocab: 3VbD:Ia&d-KhSPcl2'zNxvpHB#sL/"qQT?kiWGu90ojyn(8A1C7gFt.6EwM*X)e!4YU+,J;Rf5ZrmO
width: 128
