batch_size: 16
height: 32
learning_rate: 0.0005
max_text_length: 21
model_path: Models/03_handwriting_recognition/202503192056
train_epochs: 1000
train_workers: 20
vocab: 5L8qybk3f'cZYnQ?uNO2;KBWweRVzM&s(vFT1-Xo:,j9pJl*xG/+)4UrdD0!A#"hCI7aHtP6iEmgS.
width: 128
